---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: inspect-git-content
spec:
  params:
  workspaces:
    - name: workspace
      mountPath: /artifacts
  steps:
    - name: inspect-git-content
      image: ibmcom/pipeline-base-image:2.6
      env:
        # - name: REPOSITORY
        #   value: $(params.repository)
        # - name: DIRECTORY_NAME
        #   value: $(params.directory-name)
        # - name: GHE
        #   value: $(params.ghe)
        - name: PIPELINE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-id']
        - name: PIPELINE_RUN_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/tekton-pipeline']
        - name: WORKSPACE
          value: $(workspaces.workspace.path)
      workingDir: /artifacts
      command: ["/bin/bash", "-c"]
      args:
        - |
          env | sort
          jq -r '.' /cd-config/toolchain.json


      volumeMounts:
        - mountPath: /steps
          name: steps-volume
        - mountPath: /cd-config
          name: cd-config-volume
  volumes:
    - name: steps-volume
      emptyDir: {}
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
          - key: toolchain.json
            path: toolchain.json
