---
# Build task to build the codebase
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
spec:
  # params:
  #   - name: directory-name
  #     default: "."
  #   - name: custom-sdk-versions
  #     default: "{}"
  # results:
  #   - name: text
  #     description: Human notification text
  workspaces:
    - name: code
      mountPath: /artifacts
  steps:
    - name: build
      image: ibmcom/pipeline-base-image:2.6
      # env:
      #   - name: DIRECTORY_NAME
      #     value: $(params.directory-name)
      #   - name: WORKSPACE
      #     value: $(workspaces.code.path)
      #   - name: CUSTOM_SDK_VERSIONS
      #     value: $(params.custom-sdk-versions)
      workingDir: /artifacts
      command: ["/bin/bash", "-c"]
      args:
        - |
          #!/bin/bash
          ls -lart
          npm run build


