---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ibp-fabric-pipeline
spec:
  params:
    - name: repository
      description: the git repo containing source code. If empty, the repository url will be found from toolchain
      default: ""
    - name: branch
      description: the branch for the git repo
      default: "master"
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: pipeline-debug
      default: "0"
  workspaces:
    - name: pipeline-ws
  tasks:
    # Leaving this extract URL here - but don't believe that it's properly working with github intergations
    - name: extract-repository-url
      taskRef:
        name: toolchain-extract-value
      params:
        - name: expression
          # if a params.repository is given, it takes precedence
          value: '. as $toolchain | ["$(params.repository)"] | if .[0]=="" then $toolchain | .services[] | select(.toolchain_binding.name=="repo") | .dashboard_url else .[0] end'
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    # Clone the Chaincode/Contract Repository
    # And run a helpful debug utility
    - name: git-clone
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: branch
          value: $(params.branch)
        - name: revision
          value: $(params.revision)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: pipeline-git-event-content-inspect
      runAfter:
        - git-clone
      taskRef:
        name: inspect-git-content
      workspaces:
        - name: workspace
          workspace: pipeline-ws

    # Build the Chaincode
    # Using the node.js build task
    - name: pipeline-build-task
      taskRef:
        name: chaincode-node-build-task
      runAfter:
        - pipeline-git-event-content-inspect
      workspaces:
        - name: code
          workspace:  pipeline-ws 

    # The Chaincode now needs to be packaged
    - name: pipeline-package-task
      taskRef:
         name: chaincode-package
      runAfter:
        - pipeline-test-task
      params:
        - name: label
          value: "demo"
        - name: type
          value: "node"
        - name: dir-to-package
          value: "."
      workspaces:
        - name: code
          workspace: pipeline-ws

    - name: pipeline-ibp-credentials
      taskRef:
         name: ibp-credentials
      params:
        - name: org_ibp_api_endpoint_id
        - name: org_ibp_api_authtype_id
        - name: org_ibp_api_key_id
        - name: org_ibp_api_secret_id
        - name: org_secret_manager_url
        - name: cloud_api_key
      workspaces:
        - name: code
          workspace: pipeline-ws

    # This task needs to be performed per organization
    - name: pipeline-install-approve-task
      taskRef:
         name: chaincode-install-approve
      params:
        - name: package-tar-file
          value: $(tasks.pipeline-package-task.results.filename-package)
        - name: smart-contract-name
        - name: smart-contract-version
        - name: smart-contract-sequence
      runAfter:
        - pipeline-package-task
      workspaces:
        - name: code
          workspace:  pipeline-ws

    # This task needs to be performed per organization
    # Add a condition to this to not do if commit is required
    - name: pipeline-commit-task
      taskRef:
         name: chaincode-commit
      runAfter:
        - pipeline-install-approve-task
      workspaces:
        - name: code
          workspace:  pipeline-ws

