---
# Build task to build the codebase
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: chaincode-commit
spec:
  params:
    - name: package-tar-file
      default: "package.tgz"
  workspaces:
    - name: code
      mountPath: /artifacts
  steps:
    - name: install
      image: ibmcom/ibp-ansible:latest
      workingDir: /home/ibp-user
      command: ["/bin/bash", "-c"]
      env:
        - name: PACKAGE
          value: $(params.package-tar-file}
      args:
        - |
          #!/bin/bash
          ls -lart /artifacts
          ls -lart
          cat > install-approve.yml <<EOF
          ---
          - name: Commit chaincode
            hosts: localhost
            vars_files:
              - common-vars.yml
              - org1-vars.yml
            tasks:
              - name: Commit the chaincode on the channel
                ibm.blockchain_platform.committed_chaincode:
                  api_endpoint: "{{ api_endpoint }}"
                  api_authtype: "{{ api_authtype }}"
                  api_key: "{{ api_key }}"
                  api_secret: "{{ api_secret | default(omit) }}"
                  api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
                  peer: "{{ org1_peer_name }}"
                  identity: "{{ org1_name }} Admin.json"
                  msp_id: "{{ org1_msp_id }}"
                  channel: "{{ channel_name }}"
                  organizations:
                    - "{{ org1_name }}"
                    - "{{ org2_name }}"
                  name: "{{ smart_contract_name }}"
                  version: "{{ smart_contract_version }}"
                  sequence: "{{ smart_contract_sequence }}"
                  endorsement_policy: "{{ smart_contract_endorsement_policy | default(omit) }}"
                  collections_config: "{{ smart_contract_collections_file | default(omit) }}"
          EOF

          cat install-approve.yml
          ansible --version