---
# Build task to build the codebase
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: chaincode-install-approve
spec:
  params:
    - name: package-tar-file
      default: "package.tgz"
    - name: auth-vars-file
      default: "auth-vars.yml"
    - name: endorsement_policy
      default: "omit"
    - name: collections_config
      default: "omit"      
    - name: smart-contract-name
    - name: smart-contract-version
    - name: smart-contract-sequence
  workspaces:
    - name: code
      mountPath: /artifacts
  steps:
    - name: install
      image: ibmcom/ibp-ansible:latest
      workingDir: /home/ibp-user
      command: ["/bin/bash", "-c"]
      env:
        - name: PACKAGE
          value: $(params.package-tar-file}
        - name: AUTH_VARS
          value: $(params.auth-vars-file)
        - name: ORG_PEER_NAME
          value: $(params.org-peer-name)
        - name: ORG_ADMIN_FILE
          value: $(params.org-admin-file)
        - name: ORG_MSP_ID
          value: $(params.org-msp-id)
        - name: ENDORSEMENT_POLICY
          value: $(params.endorsement-policy)
        - name: COLLECTIONS_CONFIG
          value: $(params.collections-config)
        - name: SMART_CONTRACT_NAME
          value: $(params.smart-contract-name)
        - name: SMART_CONTRACT_VERSION
          value: $(params.smart-contract-version)
        - name: SMART_CONTRACT_SEQUENCE
          value: $(params.smart-contract-sequence)
      args:
        - |
          #!/bin/bash
          ls -lart /artifacts
          ls -lart
          cat > install-approve.yml <<EOF
          ---
          - name: Install and approve chaincode
            hosts: localhost
            vars_files:
              - /artifacts/${AUTH_VARS}
            tasks:
              - name: Install the chaincode on the peer
                ibm.blockchain_platform.installed_chaincode:
                  api_endpoint: "{{ api_endpoint }}"
                  api_authtype: "{{ api_authtype }}"
                  api_key: "{{ api_key }}"
                  api_secret: "{{ api_secret | default(omit) }}"
                  api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
                  peer: "${ORG_PEER_NAME}"
                  identity: "/artifacts/${ORG_ADMIN_FILE}"
                  msp_id: "${ORG_MSP_ID}"
                  path: "/artifacts/${PACKAGE}"
                register: result

              - name: Approve the chaincode on the channel
                ibm.blockchain_platform.approved_chaincode:
                  api_endpoint: "{{ api_endpoint }}"
                  api_authtype: "{{ api_authtype }}"
                  api_key: "{{ api_key }}"
                  api_secret: "{{ api_secret | default(omit) }}"
                  api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
                  peer: "${ORG_PEER_NAME}"
                  identity: "/artifacts/${ORG_ADMIN_FILE}"
                  msp_id: "${ORG_MSP_ID}"
                  channel: "${CHANNEL_NAME}"
                  name: "${SMART_CONTRACT_NAME}"
                  version: "${SMART_CONTRACT_VERSION}"
                  package_id: "{{ result.installed_chaincode.package_id }}"
                  sequence: "${SMART_CONTRACT_SEQUENCE}"
                  endorsement_policy: "${ENDORSEMENT_POLICY}"
                  collections_config: "${COLLECTIONS_CONFIG}"
          EOF

          cat install-approve.yml
          ansible-playbook install-approve.yml